GOSWIFT_COLUMNS = [
    "order_number",
    "customer_ID",
    "customer_company_name",
    "customer_gst_in",
    "customer_name",
    "customer_address",
    "customer_pincode",
    "customer_city",
    "customer_state",
    "customer_number",
    "customer_email",
    "delivery_type",
    "b2b_order_channel",
    "b2b_order_channel_other",
    "total_weight_gms",
    "invoice_number",
    "order_invoice_amount",
    "product_description",
    "ewaybill_number",
    "sender_gst_in",
    "pickup_location_name",
    "box_type",
    "number_of_boxes",
    "l_cms",
    "w_cms",
    "h_cms",
    "seller_courier_choice",
    "service_type",
    "is_rtv_shipment",
    "is_appointment_based",
    "appointment_date",
    "appointment_time (HHMM)",
    "appointment_id",
    "purchase_order_number",
    "purchase_order_expiry_date",
]

DEFAULT_VALUES = {
    "customer_ID": "",
    "customer_gst_in": "",
    "customer_email": "",
    "delivery_type": "",
    "b2b_order_channel_other": "",
    "sender_gst_in": "",
    "appointment_date": "",
    "appointment_time (HHMM)": "",
    "appointment_id": "",
    "purchase_order_number": "",
    "purchase_order_expiry_date": "",

    "product_description": "Cosmetics",
    "customer_number": "9999999999",
    "pickup_location_name": "RENEE Cosmetics Pvt. Ltd. B2B",

    "box_type": 1,
    "l_cms": 10,
    "w_cms": 10,
    "h_cms": 10,

    "service_type": "SURFACE",
    "is_rtv_shipment": "TRUE",
    "is_appointment_based": "TRUE",
}
